# Generated by Django 5.2.4 on 2025-07-23 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=300)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("body", models.TextField()),
                ("likes", models.PositiveIntegerField(blank=True, null=True)),
                ("dislikes", models.PositiveIntegerField(blank=True, null=True)),
                ("posted_on", models.DateTimeField(auto_now=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blogs_with_tag",
                        to="intervention_blog.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_author", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("made_on", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="intervention_blog.blog",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intervention_blog.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="intervention_blog.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="Watchings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_watch_on", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="intervention_blog.userprofile",
                    ),
                ),
                (
                    "watcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="intervention_blog.userprofile",
                    ),
                ),
            ],
        ),
    ]
