# Generated by Django 5.2.4 on 2025-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intervention_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                related_name="blogs_with_tag", to="intervention_blog.tag"
            ),
        ),
    ]
