# Generated by Django 5.2.3 on 2025-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_blog', '0002_tag_alter_blog_author_alter_comment_blog_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
