# Generated by Django 5.2.4 on 2025-10-08 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intervention_blog", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Watchings",
        ),
    ]
