# Generated by Django 5.2.3 on 2025-06-21 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_blog', '0003_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 21, 14, 30, 48, 573376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
