# Generated by Django 5.2.4 on 2025-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intervention_blog", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="dislikes",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="likes",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
