# Generated by Django 5.2.4 on 2025-09-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intervention_blog", "0003_alter_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="intervention_blog.blog",
            ),
        ),
    ]
