# Generated by Django 5.2.3 on 2025-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_blog', '0004_blog_posted_on_blog_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
